---
# tasks file for roles-p2

- name: install almalinux
  dnf:
    name: "{{ package }}"
    state: present
  when:
    - ansible_distribution | lower == 'almalinux'
    - ansible_os_family == 'RedHat'

- name: enable & start httpd
  service:
    name: "{{ package }}"
    enabled: yes
    state: started
  when:
    - ansible_distribution | lower == 'almalinux'
    - ansible_os_family == 'RedHat'

- name: Ensure /etc/httpd/conf.d directory exists
  file:
    path: /etc/httpd/conf.d
    state: directory
    mode: '0755'

- name: Copy web1 files to target
  copy:
    src: web1
    dest: "{{ dest }}/web1"
  notify: restart httpd

- name: Copy web2 files to target
  copy:
    src: web2
    dest: "{{ dest }}/web2"
  notify: restart httpd

- name: deploy web1 httpd config
  template:
    src: web1.conf.j2
    dest: /etc/httpd/conf.d/web1.conf
  notify: restart httpd

- name: deploy web2 httpd config
  template:
    src: web2.conf.j2
    dest: /etc/httpd/conf.d/web2.conf
  notify: restart httpd

- name: Open firewall ports for HTTP and HTTPS
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - http
    - https
  notify: restart firewall

- name: set selinux to permissive
  selinux:
    policy: targeted
    state: permissive
